### ISSUE TITLE
Fix install process - does MessageFOSUser class needs annotation?

### ISSUE THREAD

**Issue by mccrodp** [mccrodp/message_fos#1]
```
The following extensions will be enabled: message_fos
Do you really want to continue? (y/n): y
exception 'LogicException' with message 'Getting the base fields is not supported for entity type Message FOS User.' in                            [error]
/Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityFieldManager.php:199
Stack trace:
#0 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityFieldManager.php(171):
Drupal\Core\Entity\EntityFieldManager->buildBaseFieldDefinitions('message_fos_use...')
#1 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityFieldManager.php(394):
Drupal\Core\Entity\EntityFieldManager->getBaseFieldDefinitions('message_fos_use...')
#2 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityManager.php(152):
Drupal\Core\Entity\EntityFieldManager->getFieldStorageDefinitions('message_fos_use...')
#3 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorageSchema.php(102):
Drupal\Core\Entity\EntityManager->getFieldStorageDefinitions('message_fos_use...')
#4 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(245):
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->__construct(Object(Drupal\Core\Entity\EntityManager),
Object(Drupal\Core\Entity\ContentEntityType), Object(Drupal\Core\Entity\Sql\SqlContentEntityStorage),
Object(Drupal\Core\Database\Driver\mysql\Connection))
#5 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1356):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->getStorageSchema()
#6 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1452):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}()
#7 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1357):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object(Closure))
#8 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityTypeListener.php(71):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#9 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityManager.php(382):
Drupal\Core\Entity\EntityTypeListener->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#10 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php(135):
Drupal\Core\Entity\EntityManager->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#11 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Extension/ModuleInstaller.php(219):
Drupal\Core\Entity\EntityDefinitionUpdateManager->installEntityType(Object(Drupal\Core\Entity\ContentEntityType))
#12 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#13 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/core/drupal/environment.inc(131):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#14 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/core/drupal/environment.inc(198): drush_module_install(Array)
#15 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1167): drush_module_enable(Array)
#16 [internal function]: drush_pm_enable('message_fos')
#17 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(366): call_user_func_array('drush_pm_enable', Array)
#18 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#19 [internal function]: drush_command('message_fos')
#20 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#21 /Users/paulmccrodden/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#22 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#23 /Users/paulmccrodden/.composer/vendor/drush/drush/drush.php(12): drush_main()
#24 {main}
```

**Comment by mccrodp** [comment]
Remove annotation and install / uninstall seems successful!
